In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [43]:
from sklearn.datasets import load_iris

In [44]:
iris = load_iris()

In [45]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [46]:
l_scores = cross_val_score(LogisticRegression(),iris.data,iris.target)
l_scores

C:\Python\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [47]:
np.average(l_scores)

0.9733333333333334

In [48]:
d_scores = cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [49]:
np.average(d_scores)

0.9600000000000002

In [50]:
s_scores = cross_val_score(SVC(),iris.data,iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [51]:
np.average(s_scores)

0.9666666666666666

In [52]:
r_scores = cross_val_score(RandomForestClassifier(),iris.data,iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [53]:
np.average(r_scores)

0.96