In [41]:
import pandas as pd
import numpy as np

In [41]:
import pandas as pd
import numpy as np

In [42]:
from sklearn.datasets import load_iris
iris = load_iris()

In [43]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)

In [44]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [45]:
df["flower"] = iris.target

In [46]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [47]:
df["flower"] = df["flower"].apply(lambda x: iris.target_names[x])

In [48]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.2)

In [50]:
from sklearn.svm import SVC
model = SVC(kernel="rbf",C=30,gamma="auto")
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9666666666666667

# Approach 1

In [51]:
from sklearn.model_selection import cross_val_score

In [53]:
a=cross_val_score(SVC(kernel="linear",C=10,gamma="auto"),iris.data,iris.target,cv=5)

In [55]:
a

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [54]:
np.average(a)

0.9733333333333334

In [56]:
b=cross_val_score(SVC(kernel="rbf",C=10,gamma="auto"),iris.data,iris.target,cv=5)

In [57]:
b

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [59]:
np.average(b)

0.9800000000000001

In [60]:
c= cross_val_score(SVC(kernel="rbf",C=20,gamma="auto"),iris.data,iris.target,cv=5)

In [61]:
c

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [62]:
np.average(c)

0.9666666666666668

# Approach 2

In [67]:
kernels=["rbf","linear"]
c=[1,10,20]
avg_scores = {}
for kval in kernels:
    for cval in c:
        cv_scores = cross_val_score(SVC(kernel=kval,C=cval,gamma="auto"),iris.data,iris.target,cv=5)
        avg_scores[kval + "_" + str(cval)] = np.average(cv_scores)

avg_scores

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [68]:
from sklearn.model_selection import GridSearchCV
clf =GridSearchCV(SVC(gamma="auto"),{
    "C":[1,10,20],
    "kernel":["rbf","linear"]
},cv=5,return_train_score=False)

clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00047336, 0.0004025 , 0.00060182, 0.00039873, 0.00040011,
        0.00100741]),
 'std_fit_time': array([4.50403721e-04, 4.92957713e-04, 4.91418076e-04, 4.88387074e-04,
        4.90037648e-04, 9.43679891e-06]),
 'mean_score_time': array([0.00020008, 0.00060587, 0.00019932, 0.00019894, 0.0006001 ,
        0.00019288]),
 'std_score_time': array([0.00040016, 0.00049489, 0.00039864, 0.00039787, 0.00048998,
        0.00038576]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [69]:
df = pd.DataFrame(clf.cv_results_)

In [70]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.000473      0.000450         0.000200        0.000400       1   
1       0.000402      0.000493         0.000606        0.000495       1   
2       0.000602      0.000491         0.000199        0.000399      10   
3       0.000399      0.000488         0.000199        0.000398      10   
4       0.000400      0.000490         0.000600        0.000490      20   
5       0.001007      0.000009         0.000193        0.000386      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [71]:
df[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [72]:
clf.best_score_

0.9800000000000001

In [73]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [95]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma="auto"),{
    "C":[1,10,20],
    "kernel":["rbf","linear"]
},cv=5,return_train_score=False,n_iter=2)

In [96]:
rs.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [97]:
pd.DataFrame(rs.cv_results_)[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0      20          rbf         0.966667
1       1       linear         0.980000

In [98]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [110]:
model_params = {
    "SVM":{
        "model": SVC(gamma="auto"),
        "params":{
            "C":[1,10,20],
            "kernel":["rbf","linear"]
        }
    },
    "ramdom_forest":{
        "model" : RandomForestClassifier(),
        "params" : {
            "n_estimators":[1,5,10]
        }
    },
    "logistic_regression" : {
        "model" : LogisticRegression(solver="liblinear",multi_class="auto"),
        "params": {
            "C":[1,5,10]
        }
    }
}

In [112]:
scores = []

for model_name , mp in model_params.items():
    clf=GridSearchCV(mp["model"], mp["params"],cv=5,return_train_score=False)
    clf.fit(iris.data,iris.target)
    scores.append({
        "model":model_name,
        "best_scores": clf.best_score_,
        "best_params":clf.best_params_
    })

In [113]:
df = pd.DataFrame(scores,columns = ["model","best_scores","best_params"])
df

model  best_scores                best_params
0                  SVM     0.980000  {'C': 1, 'kernel': 'rbf'}
1        ramdom_forest     0.966667        {'n_estimators': 5}
2  logistic_regression     0.966667                   {'C': 5}