In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits
digits = load_digits()

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [7]:
df = pd.DataFrame(digits.data,columns=digits.feature_names)

In [8]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [12]:
df["Target"] = digits.target

In [13]:
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_7_0  pixel_7_1  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        0.0        0.0   
3        0.0        0.0        0.0        8.0  ...        0.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  pixel_7_6  pixel_7_7  Digit  \
0        6.0       13.0       10.0        0.0        0.0        0.0      0   
1        0.0       11.0       16.0       10.0        0.0        0.0      1   
2        0.0        3.0       11.0       16.0        9.0        0.0      2   
3        7.0       13.0       13.0        9.0        0.0        0.0      3   
4        0.0        2.0       16.0        4.0        0.0        0.0      4   

   Target  
0       0  
1       1  
2       2  
3       3  
4       4  

[5 rows x 66 columns]

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [20]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9805555555555555

In [21]:
from sklearn.svm import SVC
model = SVC(kernel="rbf",C=30,gamma="auto")
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.46944444444444444

Approach 1 for hyperparameter

In [22]:
from sklearn.model_selection import cross_val_score

In [25]:
a = cross_val_score(SVC(kernel="linear",C=10,gamma="auto"),digits.data,digits.target,cv=5)

In [26]:
a

array([0.96388889, 0.91944444, 0.96657382, 0.9637883 , 0.92479109])

In [27]:
np.average(a)

0.9476973073351903

In [28]:
b = cross_val_score(SVC(kernel="rbf",C=10,gamma="auto"),digits.data,digits.target,cv=5)

In [29]:
b

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

In [30]:
np.average(b)

0.47636645001547506

In [31]:
c = cross_val_score(SVC(kernel="rbf",C=20,gamma="auto"),digits.data,digits.target,cv=5)

In [32]:
c

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

In [33]:
np.average(c)

0.47636645001547506

Approach 2 hyperparameter

In [38]:
kernels = ["rbf","linear"]
c=[1,10,20]
avg_scores = {}
for kval in kernels :
    for cval in c:
        cv_scores = cross_val_score(SVC(kernel=kval,C=cval,gamma="auto"),digits.data,digits.target,cv=5)
        avg_scores[kval+"_"+str(cval)] = np.average(cv_scores)
avg_scores

{'rbf_1': 0.448545341999381,
 'rbf_10': 0.47636645001547506,
 'rbf_20': 0.47636645001547506,
 'linear_1': 0.9476973073351903,
 'linear_10': 0.9476973073351903,
 'linear_20': 0.9476973073351903}

Approach 3

In [42]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(SVC(gamma="auto"),{
    "C":[1,10,20],
    "kernel":["rbf","linear"]
},cv=5,return_train_score=False)
clf.fit(digits.data,digits.target)
clf.cv_results_

{'mean_fit_time': array([0.37157955, 0.03940635, 0.37128968, 0.04121714, 0.37021332,
        0.03839955]),
 'std_fit_time': array([0.0063881 , 0.00196629, 0.00689813, 0.00306455, 0.01175677,
        0.00173914]),
 'mean_score_time': array([0.11403012, 0.00820174, 0.11262622, 0.00939755, 0.10962615,
        0.0084064 ]),
 'std_score_time': array([0.0082947 , 0.00039999, 0.00940455, 0.00195417, 0.00459005,
        0.00049542]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [43]:
df = pd.DataFrame(clf.cv_results_)

In [44]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.371580      0.006388         0.114030        0.008295       1   
1       0.039406      0.001966         0.008202        0.000400       1   
2       0.371290      0.006898         0.112626        0.009405      10   
3       0.041217      0.003065         0.009398        0.001954      10   
4       0.370213      0.011757         0.109626        0.004590      20   
5       0.038400      0.001739         0.008406        0.000495      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.411111   
1       linear   {'C': 1, 'kernel': 'linear'}           0.963889   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.452778   
3       linear  {'C': 10, 'kernel': 'linear'}           0.963889   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.452778   
5       linear  {'C': 20, 'kernel': 'linear'}           0.963889   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.450000           0.454039           0.448468           0.479109   
1           0.919444           0.966574           0.963788           0.924791   
2           0.469444           0.479109           0.479109           0.501393   
3           0.919444           0.966574           0.963788           0.924791   
4           0.469444           0.479109           0.479109           0.501393   
5           0.919444           0.966574           0.963788           0.924791   

   mean_test_score  std_test_score  rank_test_score  
0         0.448545        0.021761                6  
1         0.947697        0.020978                1  
2         0.476366        0.015784                4  
3         0.947697        0.020978                1  
4         0.476366        0.015784                4  
5         0.947697        0.020978                1

In [45]:
df[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0       1          rbf         0.448545
1       1       linear         0.947697
2      10          rbf         0.476366
3      10       linear         0.947697
4      20          rbf         0.476366
5      20       linear         0.947697

In [46]:
clf.best_score_

0.9476973073351903

In [47]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [53]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma="auto"),{
    "C":[1,10,20],
    "kernel":["rbf","linear"]
},cv=5,return_train_score=False,n_iter=2)

In [54]:
rs.fit(digits.data,digits.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [55]:
pd.DataFrame(rs.cv_results_)[["param_C","param_kernel","mean_test_score"]]


param_C param_kernel  mean_test_score
0      20       linear         0.947697
1       1          rbf         0.448545

In [56]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [62]:
model_params = {
    "SVM":{
        "model":SVC(gamma="auto"),
        "params":{
            "C":[1,10,20],
            "kernel":["rbf","linear"]
        }
    },
    "random_forest":{
        "model": RandomForestClassifier(),
        "params" : {
            "n_estimators":[1,5,10]
        }
    },
    "logistic_regression":{
        "model":LogisticRegression(solver="liblinear",multi_class= "auto"),
        "params":{
            "C":[1,5,10]
        }
    }
}

In [63]:
scores = []
for model_name, mp in model_params.items():
    clf=GridSearchCV(mp["model"],mp["params"],cv=5,return_train_score=False)
    clf.fit(digits.data , digits.target)
    scores.append({
        "model":model_name,
        "best_scores":clf.best_score_,
        "best_params":clf.best_params_
    })

In [64]:
df = pd.DataFrame(scores,columns = ["model","best_scores","best_params"])
df

model  best_scores                   best_params
0                  SVM     0.947697  {'C': 1, 'kernel': 'linear'}
1        random_forest     0.907103          {'n_estimators': 10}
2  logistic_regression     0.922114                      {'C': 1}